spring.application.name=project-e-commerce

spring.datasource.url=jdbc:mysql://localhost:3306/projetecommerce?useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuration JPA/Hibernate pour mySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
server.address=0.0.0.0
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true